CREATE TABLE STUDENT 
(SID INT,
NAME VARCHAR(40),
DOB VARCHAR(40),
PHY INT,
CHE INT,
MAT INT);
INSERT INTO STUDENT VALUES(1,'ANU','12-07-1998',66,77,77),(2,'ANISHA','23-01-2000',88,55,99),(3,'ALBIN','07-05-2005',88,99,78),(4,'ALPHU','23-07-1997',76,87,34),(5,'MERCY','10-02-1995',99,99,99);

SELECT NAME as youngestStudent, DOB as dateOfBirth
FROM STUDENT
WHERE DOB = (SELECT min(DOB) FROM STUDENT);
SELECT SID,NAME FROM STUDENT WHERE MAT  ^ 40 AND(PHY ^ 40 OR CHE ^ 40);
ALTER TABLE STUDENT ADD COLUMN TOTAL INT;
ALTER TABLE STUDENT ADD COLUMN AVR INT;
/*SELECT SID,NAME,DOB,PHY+CHE+MAT AS TOTAL ,PHY+CHE+MAT/3 AS AVR FROM STUDENT;*/

SELECT SID,NAME,DOB,MAT FROM STUDENT ORDER BY MAT DESC;
SELECT SID,NAME,DOB,CHE FROM STUDENT ORDER BY CHE ;

UPDATE STUDENT SET TOTAL=(SELECT PHY+CHE+MAT AS TOTAL);
UPDATE STUDENT SET AVR=(SELECT TOTAL/3 AS AVR);
select * from STUDENT where MAT >=40 and (PHY >=40 or CHE >=40);
ALTER TABLE STUDENT RENAME COLUMN AVR TO AVG_MARK;
SELECT *FROM STUDENT;
SELECT AVG(AVG_MARK) FROM STUDENT;
SELECT * FROM STUDENT
WHERE AVG_MARK > (SELECT AVG(AVG_MARK) FROM STUDENT);
SELECT COUNT(SID) FROM STUDENT
WHERE AVG_MARK > (SELECT AVG(AVG_MARK) FROM STUDENT);